spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server.petclinic:8888/}
    cloud:
    gateway:
      routes:
        - id: vets-service
          uri: http://internal-petclinic-internal-alb-378481021.us-east-2.elb.amazonaws.com/api/vet/
          predicates:
            - Path=/api/vet/**
        - id: visits-service
          uri: http://internal-petclinic-internal-alb-378481021.us-east-2.elb.amazonaws.com/api/visits
          predicates:
            - Path=/api/visit/**
        - id: customers-service
          uri: http://internal-petclinic-internal-alb-378481021.us-east-2.elb.amazonaws.com/api/customer/
          predicates:
            - Path=/api/customer/**



---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server.petclinic:8888

