spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server.petclinic:8888/}
  cloud:
    gateway:
      routes:
        - id: vets-service
          uri: http://petclinic-alb-1231151435.us-east-2.elb.amazonaws.com/api/vet
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: http://petclinic-alb-1231151435.us-east-2.elb.amazonaws.com/api/visit
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://petclinic-alb-1231151435.us-east-2.elb.amazonaws.com/api/customer
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2



---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server.petclinic:8888
