CREATE DATABASE IF NOT EXISTS petclinic;
GRANT ALL PRIVILEGES ON petclinic.* TO 'pc'@'172.20.1.%' IDENTIFIED BY 'pc';
GRANT ALL PRIVILEGES ON petclinic.* TO 'pc'@'172.20.2.%' IDENTIFIED BY 'pc';
GRANT ALL PRIVILEGES ON petclinic.* TO 'pc'@'172.20.3.%' IDENTIFIED BY 'pc';
GRANT ALL PRIVILEGES ON petclinic.* TO 'pc'@'172.20.4.%' IDENTIFIED BY 'pc';

USE petclinic;

CREATE TABLE IF NOT EXISTS visits (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  pet_id INT(4) UNSIGNED NOT NULL,
  visit_date DATE,
  description VARCHAR(8192),
  FOREIGN KEY (pet_id) REFERENCES pets(id)
) engine=InnoDB;
